### ISSUE TITLE
Pull down menu for Perl version

### ISSUE THREAD

**Issue by djerius** [Grinnz/cpan-deps-graph#4]
First off, this is cool.  Thanks a lot for this!

Could you add a pull down menu for the Perl version instead of a text entry field?

Thanks!

Diab

**Comment by Grinnz** [comment]
I thought about this, I think it is a good idea. It will just need converting from the various ways you can write a perl version into the normalized entry. I can get the Perl versions from Module::CoreList.

**Comment by Grinnz** [comment]
This is implemented.

**Comment by djerius** [comment]
Thanks!
